version: '3.9'
services:

  # Setup base environment
  base:
    container_name: ide-base
    image: ide-base:latest
    hostname: machine
    build:
      context: .
      dockerfile: ./base.Dockerfile
      args:
        - HOME=/root
        # Local
        - TZ=America/Chicago
        - LANGUAGE=en
        - LANG=en_US.UTF-8
        - LC_ALL=en_US.UTF-8
        # XDG
        - XDG_CONFIG_HOME=~/.config
        - XDG_CACHE_HOME=~/.cache
        - XDG_DATA_HOME=~/.local/share
        - XDG_STATE_HOME=~/.local/state
        - XDG_BIN_HOME=~/.local/bin
        - XDG_FONTS_HOME=~/.local/fonts
        # Golang
        # - GOROOT=~/.local/share/go
        - GOLANG_VER=1.17
        - GOPATH=~/go
        # Rust
        - CARGO_HOME=~/.cargo
        # - RUSTUP_HOME=${RUSTUP_HOME}
        # Node
        - NODE_VER=14.17.5
        - NODE_ENVIRONMENT=development

  # Setup local dev environment
  local:
    env_file:
      - .env
    container_name: ide-local
    image: ide-local:latest
    hostname: machine
    build:
      context: .
      dockerfile: ./local.Dockerfile
      args:
        # User
        - USERNAME=${USERNAME}
        - HOME=${HOME}
        - PASSWORD=${PASSWORD}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - GROUPNAME=${GROUPNAME}
        - HOSTNAME=${HOSTNAME}
        - WORKSPACE=${WORKSPACE}
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_EMAIL=${GIT_EMAIL}
        # - EDITOR=${EDITOR}
        - TZ=${TZ}
        - LANGUAGE=${LANGUAGE}
        - LANG=${LANG}
        - LC_ALL=${LC_ALL}
        # Shell 
        # - SHELL_SESSIONS_DISABLE=${SHELL_SESSIONS_DISABLE}
        - SHELL=${SHELL}
        - TERM=${TERM}
        # XDG
        # - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
        - XDG_CONFIG_HOME=${XDG_CONFIG_HOME}
        - XDG_CACHE_HOME=${XDG_CACHE_HOME}
        - XDG_DATA_HOME=${XDG_DATA_HOME}
        - XDG_STATE_HOME=${XDG_STATE_HOME}
        - XDG_BIN_HOME=${XDG_BIN_HOME}
        - XDG_FONTS_HOME=${XDG_FONTS_HOME}
        # Oh-my-zsh
        - KEEP_ZSHRC=${KEEP_ZSHRC}
        - ZSH=${ZSH}
        - ZSH_CUSTOM=${ZSH_CUSTOM}
        # ZSH
        - ZDOTDIR=${ZDOTDIR}
        - GLOBALS_FILE=${GLOBALS_FILE}
        # NODE
        - NVM_DIR=${NVM_DIR}
        - NODE_VER=${NODE_VER}
        - NODE_ENVIRONMENT=${NODE_ENVIRONMENT} 
        - GOPATH=${GOPATH}
        # Dotfiles
        - DOTFILES=${DOTFILES}

  # Setup editors, language server, linters, and formatters
  # for dev environment
  editor:
    env_file:
      - .env
    container_name: ide-editor 
    image: ide-editor:latest
    hostname: machine
    build:
      context: .
      dockerfile: ./editor.Dockerfile
      args:
        # Neovim
        - EDITOR=${EDITOR} 
        - NEOVIM_VER=${NEOVIM_VER}
        - NEOVIM_DIR=${NEOVIM_DIR}
    # volumes:
    #   - ./volume/zsh:${ZDOTDIR}
