version: '3.9'
services:

  # Setup base environment
  base:
    env_file:
      - .env
    container_name: ide-base
    image: ide-base:latest
    hostname: machine
    build:
      context: .
      dockerfile: ./base.Dockerfile
      args:
        - TZ=${TZ}
        - LANG=${LANG}
        - LC_ALL=${LC_ALL}
        - LANGUAGE=${LANGUAGE}

  # Setup local dev environment
  local:
    env_file:
      - .env
    container_name: ide-local
    image: ide-local:latest
    hostname: machine
    build:
      context: .
      dockerfile: ./local.Dockerfile
      args:
        # User
        - USERNAME=${USERNAME}
        - HOME=${HOME}
        - PASSWORD=${PASSWORD}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - GROUPNAME=${GROUPNAME}
        - HOSTNAME=${HOSTNAME}
        - WORKSPACE=${WORKSPACE}
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_EMAIL=${GIT_EMAIL}
        - EDITOR=${EDITOR}
        - TZ=${TZ}
        - LANGUAGE=${LANGUAGE}
        - LANG=${LANG}
        - LC_ALL=${LC_ALL}
        # Shell 
        - SHELL=${SHELL}
        - SHELL_SESSIONS_DISABLE=${SHELL_SESSIONS_DISABLE}
        - TERM=${TERM}
        # XDG
        - XDG_CONFIG_HOME=${XDG_CONFIG_HOME}
        - XDG_CACHE_HOME=${XDG_CACHE_HOME}
        - XDG_DATA_HOME=${XDG_DATA_HOME}
        - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
        - XDG_STATE_HOME=${XDG_STATE_HOME}
        - XDG_BIN_HOME=${XDG_BIN_HOME}
        - XDG_FONTS_HOME=${XDG_FONTS_HOME}
        # Oh-my-zsh
        - KEEP_ZSHRC=${KEEP_ZSHRC}
        - ZSH=${ZSH}
        - ZSH_CUSTOM=${ZSH_CUSTOM}
        # ZSH
        - ZDOTDIR=${ZDOTDIR}
        - GLOBALS_FILE=${GLOBALS_FILE}
        # NODE
        - NVM_DIR=${NVM_DIR}
        - NODE_VER=${NODE_VER}
        - NODE_ENVIRONMENT=${NODE_ENVIRONMENT} 
        # Rust
        - CARGO_HOME=${CARGO_HOME}
        - RUSTUP_HOME=${RUSTUP_HOME}
        # Golang
        - GOLANG_VER=${GOLANG_VER}
        - GOROOT=${GOROOT} 
        - GOPATH=${GOPATH}
        # Dotfiles
        - DOTFILES=${DOTFILES}
    # volumes:
    #   - ./volume/zsh:${ZDOTDIR}

  # Setup editors, language server, linters, and formatters
  # for dev environment
  editor:
    env_file:
      - .env
    container_name: ide-editor 
    image: ide-editor:latest
    hostname: machine
    build:
      context: .
      dockerfile: ./editor.Dockerfile
      args:
        # Neovim
        - NEOVIM_VER=${NEOVIM_VER}
        - NEOVIM_DIR=${NEOVIM_DIR}
