version: '3.8'

###
# *Use docker-compose run not docker-compose start 
# Run: docker compose run --rm editor
# Build: docker compose build --no-cache
###

services:

  ide-base:
    container_name: ide-base-container
    env_file: .env
    # Set user
    # user: "${USER_ID}:${GROUP_ID}"
    image: ide-base:latest
    # Build image
    hostname: ${HOSTNAME}
    build:
      context: .
      dockerfile: base.Dockerfile
      # Define args for Dockerfile
      args:
        # User config
        - BUILD_USERNAME=${USERNAME}
        - BUILD_PASSWORD=${PASSWORD}
        - BUILD_USER_ID=${USER_ID}
        - BUILD_GROUPNAME=${GROUPNAME}
        - BUILD_GROUP_ID=${GROUP_ID}
        - BUILD_HOSTNAME=${HOSTNAME}
        - BUILD_GIT_USERNAME=iamcrash
        - BUILD_GIT_EMAIL=crash.machine@icloud.com
        - BUILD_TZ=America/Chicago
        - BUILD_TERM=xterm-256color
        - BUILD_LANGUAGE=en_US.en
        - BUILD_LANG=en_US.UTF-8
        - BUILD_LC_ALL=en_US.UTF-8
        - BUILD_SHELL=/usr/bin/zsh
        - BUILD_EDITOR=nvim
        - BUILD_NODE_ENV=dev
        - BUILD_NODE_VER=14.17.5
        - BUILD_NEOVIM_VER=0.5.0

  ide-main:
    container_name: ide-main-container
    env_file: .env
    # Set user
    # user: "${USER_ID}:${GROUP_ID}"
    image: ide-main:latest
    # Build image
    hostname: ${HOSTNAME}
    build:
      context: .
      dockerfile: main.Dockerfile
    volumes:
      - "./workspace:/home/${USERNAME}/workspace"


