version: '3.8'

# Run /bin/zsh
# docker compose run --rm editor
services:
  ide-base:
    container_name: ide-base-container
    # Set user
    # user: "${USER_ID}:${GROUP_ID}"
    image: ide-base:latest
    # Build image
    build:
      context: .
      dockerfile: base.Dockerfile
      # Define args for Dockerfile
      args:
        # User config
        - BUILD_USERNAME=crash
        - BUILD_PASSWORD=password
        - BUILD_USER_ID=1001
        - BUILD_GROUP_ID=1001
        - BUILD_GROUPNAME=crash
        - BUILD_GIT_USERNAME=iamcrash
        - BUILD_GIT_EMAIL=crash.machine@icloud.com
        - BUILD_TZ=America/Chicago
        - BUILD_TERM=xterm-256color
        - BUILD_LANGUAGE=en_US.en
        - BUILD_LANG=en_US.UTF-8
        - BUILD_LC_ALL=en_US.UTF-8
        - BUILD_SHELL=/usr/bin/zsh
        - BUILD_EDITOR=nvim
        - BUILD_NODE_ENV=dev
        - BUILD_NODE_VER=14.17.5
        - BUILD_NEOVIM_VER=0.5.0

  ide-test:
    container_name: ide-test-container
    # Set user
    # user: "${USER_ID}:${GROUP_ID}"
    image: ide-test:latest
    # Build image
    build:
      context: .
      dockerfile: test.Dockerfile

  ide-main:
    container_name: ide-main-container
    # Set user
    # user: "${USER_ID}:${GROUP_ID}"
    image: ide-main:latest
    # Build image
    build:
      context: .
      dockerfile: main.Dockerfile


      # Define args for Dockerfile
          # Other paths
# Overlay network create virtual network for multiple host
# Bridge network creates virtual network for same host
# networks:
#   ide:
#     driver: overlay        
#     # attacheable: true
